apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: couchbase
  name: couchbase
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: couchbase
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: couchbase
    spec:
      containers:
      - env:
        - name: COUCHBASE_ADMINISTRATOR_PASSWORD
          value: "123456"
        - name: COUCHBASE_ADMINISTRATOR_USERNAME
          value: root
        image: 161112291/dailycodebuffer:couchbase
        imagePullPolicy: "Never"
        name: couchbase
        ports:
        - containerPort: 8091
        - containerPort: 8092
        - containerPort: 8093
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/couchbase
          name: couchbase-database-data-volume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: couchbase-database-data-volume
        persistentVolumeClaim:
          claimName: couchbase-database-data-volume
status: {}
